# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa02f7415343a81fbaafa607a3ea0928b05dc596a390c1c56b9bbf2b282578354f35e778b483aafe33aef564f2de1e3fa5acd9d03e63e729aa4106284bfca96a

test:
  secret_key_base: 2b9601f225aba6a4777e8103fdf5ddd86a5d5718d1a02bcc757c663614270e72148c459e8803b887d73e764ccdf1465c8f25d18f347373c6c1a51981681ae0cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
